# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='group',
            field=models.CharField(blank=True, max_length=256, verbose_name='Group media'),
        ),
    ]
