# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_media_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_type',
            field=models.CharField(blank=True, editable=False, max_length=256, verbose_name='File type'),
        ),
    ]
