# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_media_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_type',
            field=models.CharField(blank=True, choices=[(b'image', 'Image'), (b'video', 'Video'), (b'attached', 'Attached')], default=b'image', max_length=256, verbose_name='File type'),
        ),
    ]
