# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20160310_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='media',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='media',
            name='file_type',
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(blank=True, choices=[(b'image', 'Image'), (b'video', 'Video'), (b'file', 'File')], default=b'image', max_length=32, verbose_name='File type'),
        ),
        migrations.AlterField(
            model_name='media',
            name='group',
            field=models.CharField(blank=True, max_length=64, verbose_name='Group media'),
        ),
    ]
