# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import helpful.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20160310_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='page',
        ),
        migrations.AlterField(
            model_name='page',
            name='img',
            field=models.FileField(blank=True, upload_to=helpful.fields.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='pages', to='sites.Site', verbose_name='Sites'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='A slug is the part of a URL which identifies a page using human-readable keywords', max_length=128, unique=True, verbose_name='Slug'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
