# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-02 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('pages', '0006_auto_20160621_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('referer', models.URLField(max_length=4096, verbose_name='URL')),
                ('user_agent', models.CharField(max_length=4096, verbose_name='User agent')),
                ('ip', models.GenericIPAddressField(verbose_name='Site')),
                ('url', models.URLField(max_length=4096, verbose_name='URL')),
                ('datatime', models.DateTimeField(auto_now_add=True, verbose_name='Date and time')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content Type')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
