# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helpful.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Description')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('image', models.FileField(blank=True, null=True, upload_to=helpful.fields.upload_to, verbose_name='Image')),
                ('bg', models.FileField(blank=True, null=True, upload_to=helpful.fields.upload_to, verbose_name='Background')),
                ('order', models.PositiveIntegerField(default=500, verbose_name='Sort ordering')),
                ('group', models.CharField(default=b'content', max_length=64, verbose_name='Area')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_subblocks', to='pages.Block', verbose_name='Parent')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
            },
        ),
    ]
