# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='pages.Block', verbose_name='Blocks'),
        ),
    ]
