# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20170202_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='parent',
        ),
    ]
